[package]
name = "clap-config"
version = "0.1.0"
authors = ["Konstantin Stepanov <konstantin.s@p2p.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2"
config = "0.11"
